### PR TITLE
Report Feature Bugs Fix

### LINKED ISSUE #150: Report Feature Bugs
Your final ticket is to fix any bugs/issues with the report feature. Here is a list of bugs and issues that I found, but if you find any that are not mentioned here, please fix them as well! **The ticket is due on April 24 @ 10 PM and revisions are due on April 26 @ 5 PM.** These are hard deadlines as we need to have this ticket fully completed by Friday so that I can prepare the deployment for showcase and make sure everything is bug-free! As always, let me know if you guys have any questions. We are so close to the finish line! :)

- [x] Set the default state of the admin report view to display the reports in each section ("Unread Reports", "High Priority", ...). Currently, each section default to a hidden state, requiring additional clicks to view their contents. We want it to be the reverse.
- [x] Adjust the admin report view so that it contains "Subject", "Submitted By", "Person Reported", "Time Submitted". The involves deleting the field "Title" and adding "Person Reported" as the 3rd column. Similarly to the "Submitted By" column, make sure that the reported psychiatrists' full names are displayed under the "Person Reported" column.

- [x] Change the title of the admin report modal from "Report Subject" to "Report Information". We will not be having a title/report subject field for reports.
- [x] In the admin report modal, add a line under "Submitted By: [Patient Name]" for "Person Reported: [Psychiatrist Name]". 
Image

- [x] Make sure the Cancel and Assign Priority buttons are the color `#519AEB`. 
Image

- [x] Match the design of the Assign Priority dropdown to the Figma design.
Image

- [x] Make sure the assign priority dropdown is always directly under the Assign Priority button. 

1. One example where it isn't under the Assign Priority button: Image

2. Another example when viewing this on an iPhone 12 Pro: Image

### PR DESCRIPTION
**Pull request by alishav14**
## Overview

We worked on fixing the bugs and styling to make a more consistent design, focusing mostly on the admin report page and the report popup that opens when a report is clicked in the AdminReport.tsx file. By fixing the columns and adding the new "Submitted By" column that stored the psychiatrist data from the firebase, we created a more user-friendly and more easily-understandable interface. Additionally, with work on the "Assign Priority" button in the poppup, we were able to create a design that more closely resembled the Figma.

## Replication

To test the code, clone the repository, cd frontend, and yarn run dev the terminal. Sign into an admin account after accessing the localhost. Then, navigate to the "reports" tab in the navigation bar at the top right. This is the essentially the page we worked on for this ticket. There, you can toggle the chevron symbols to open and close the reports of each priority, spam, or unread. If there are no reports under a certain category, no reports will be displayed when you toggle the button. When clicking on a report, and then clicking the "Assign Priority" button, the opened options list allows a user to assign a new priority to the report.

## Changes Made

We worked on making the styling of the Admin Reports page more closely resembling the Figma, as well as implementing a better design. This involved deleting the Report Title column and replacing it with a "Submitted By" column that now allows an admin to see who is being reported with each client report. Additionally, the button colors match the blue theme of the interface, and the report popup now includes the psychiatrist being reported, as well as a better dropdown styling.

## Test Coverage

To test the new implemented features, we worked on creating test reports from a client account, and first ensuring they appear in the "Unread Report" category. Then, we ensured the correct psychiatrist that was reported displayed in the new "Submitted By" column. Additionally, when a report was clicked, the name of that psychiatrist should also be seen at the top, and the dropdown at the bottom of the popup should show the options in a manner resembling the Figma. The options should also be clickable, and change the priority state of each report when clicked on.

## Next Steps 

In the next steps, we will work on improving the dropdown appearance for each of the options when the "Assign Priority" button is clicked in the popup.

## Related PRs or Issues

This is related to our PR #141 and issue #150 . In this PR, we worked on creating the Admin Report page, where an admin can assign priorities to each report, which changes the priority state. Additionally, we worked on creating the report popup, which displays additional details about each report when it is clicked on.

## Screenshots

<details>

The new "Submitted By" column showing the psychiatrists that are submitted

download

The "Person Submitted" can be seen in the popup

download

The Assign Priority dropdown

download

</details>

### CODE REVIEW

File: frontend/src/components/AdminReport.tsx [hunk 1]
```diff
@@ -300,9 +376,9 @@ const AdminReport = () => {
 
         <div className='flex items-center lg:mx-36' style={{ alignSelf: 'stretch', height: 70, flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'center', gap: 10, display: 'flex' }}>
           <div className=' flex justify-between items-center w-full px-5 md:px-12' style={{ alignSelf: 'stretch', paddingTop: 10, paddingBottom: 10, justifyContent: 'space-between', alignItems: 'center', display: 'inline-flex' }}>
-            <div style={{ color: 'black', fontSize: 16, fontWeight: '700', wordWrap: 'break-word' }}>Title</div>
             <div style={{ color: 'black', fontSize: 16, fontWeight: '700', wordWrap: 'break-word' }}>Subject</div>
             <div style={{ color: 'black', fontSize: 16, fontWeight: '700', wordWrap: 'break-word' }}>Submitted By</div>
+            <div style={{ color: 'black', fontSize: 16, fontWeight: '700', wordWrap: 'break-word' }}>Person Reported</div>
```
Comment (amywu4) [inline frontend/src/components/AdminReport.tsx]: Actually, change this to "Psychiatrist Reported".

File: frontend/src/components/ReportPopup.tsx [hunk 2]
```diff
@@ -36,6 +36,7 @@ const ReportPopup = ({ report }) => {
     <div style={cardStyle} className="card bg-base-100  mb-4">
       <div>
         <h2 style={{ marginBottom: '10px' }} className="font-bold">Submitted By: <span className="font-normal">{report.reporter_name}</span> </h2>
+        <h2 style={{ marginBottom: '10px' }} className="font-bold">Person Reported: <span className="font-normal">{report.reporter_name}</span> </h2>
```
Comment (amywu4) [inline frontend/src/components/ReportPopup.tsx]: Change this to "Psychiatrist Reported" as well.
Also, this line should display "Psychiatrist Reported: [Psychiatrist Name]", but it currently displays the reporter's name instead of the psychiatrist's name.

File: frontend/src/components/AdminReport.tsx [hunk 3]
```diff
@@ -220,71 +243,124 @@ const AdminReport = () => {
...
+      marginTop: '20px'
     };
 
-    const dropdownStyle = {
-      backgroundColor: '#007BFF',
+    const cancelButtonStyle = {
+      backgroundColor: 'white',
+      color: 'black',
+      padding: '8px',
+      borderRadius: '5px',
```
Comment (amywu4) [inline frontend/src/components/AdminReport.tsx]: Make this borderRadius: '10 px'

File: frontend/src/components/AdminReport.tsx [hunk 4]
```diff
@@ -220,71 +243,124 @@ const AdminReport = () => {
...
+      border: '2px solid #519AEB',
+      cursor: 'pointer',
+    };
+
+    const assignPriorityButtonStyle: React.CSSProperties = {
+      backgroundColor: '#519AEB',
       color: 'white',
       padding: '8px',
       borderRadius: '5px',
```
Comment (amywu4) [inline frontend/src/components/AdminReport.tsx]: Make this borderRadius: '10 px'

File: frontend/src/components/AdminReport.tsx [hunk 5]
```diff
@@ -220,71 +243,124 @@ const AdminReport = () => {
...
       gap: '8px',
-      marginTop: '20px' // Adds some space between the buttons and other elements above
+      marginTop: '20px'
     };
 
-    const dropdownStyle = {
-      backgroundColor: '#007BFF',
+    const cancelButtonStyle = {
+      backgroundColor: 'white',
+      color: 'black',
```
Comment (amywu4) [inline frontend/src/components/AdminReport.tsx]: Change the color to okb_colors.dark_gray (a color defined in colors.ts). The okb_colors import is already at the top of the file.

**Review by amywu4 — CHANGES_REQUESTED** [review]
Nice work! :) I added some comments for super small adjustments that need to be made. As discussed, try to make the Assign Priority dropdown overlay over the modal instead of inside the modal so it doesn't result in a scroll bar. Also, make the width of the button and the dropdown match up. They are currently a bit mismatched as shown in the image below.
Screenshot 2024-04-24 at 10 40 39 PM
Lastly, to make the repository a bit cleaner, could you guys create a folder called `adminReport` in the `components` folder and move these two files (`AdminReport.tsx` and `ReportPopup.tsx`) into it? Thanks!

**Review by amywu4 — APPROVED** [review]
LGTM! :)
